//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WeaselDeployer.rc
//
#define IDC_MYICON                      2
#define IDD_WEASELDEPLOYER_DIALOG       102
#define IDI_WEASELDEPLOYER              107
#define IDI_SMALL                       108
#define IDR_MAINFRAME                   128
#define IDD_SWITCHER_SETTING            129
#define IDD_STYLE_SETTING               130
#define IDI_DEPLOY                      131
#define IDD_DICT_MANAGEMENT             132
#define IDS_STR_WEASEL                  133
#define IDS_STR_SAD                     134
#define IDS_STR_HAPPY                   135
#define IDS_STR_NOT_REGULAR             136
#define IDS_STR_DEPLOYING_RESTARTREQ    137
#define IDS_STR_DEPLOYING_WAIT          138
#define IDS_STR_SEL_EXPORT_DICT_NAME    139
#define IDS_STR_ERREXPORT_SYNC_UV       140
#define IDS_STR_ERR_EXPORT_UNKNOWN      141
#define IDS_STR_ERR_EXPORT_SNAP_LOST    142
#define IDS_STR_ERR_UNKNOW              143
#define IDS_STR_ERR_UNKNOWN             143
#define IDS_STR_ERR_SUCCESS             144
#define IDS_STR_ERR_EXPORT_FILE_LOST    145
#define IDS_STR_SEL_IMPORT_DICT_NAME    146
#define IDS_STR_ERR_AT_LEAST_ONE_SEL    147
#define IDS_STR_SCHEMA_NAME             148
#define IDS_STR_OPEN                    149
#define IDS_STR_SAVE_AS                 150
#define IDS_STR_ALL_FILES               151
#define IDS_STR_TXT_FILES               152
#define IDS_STR_IMPORTED                153
#define IDS_STR_EXPORTED                154
#define IDS_STR_RECORD_COUNT            155
#define IDS_STR_DICT_SNAPSHOT           156
#define IDS_STR_KCSS_DICT_SNAPSHOT      157
#define IDS_STR_HELP                    158
#define IDS_STR_SCHEME_ACRYLIC          159
#define IDS_STR_SCHEME_NORMAL           160
#define IDS_STR_SCHEME_FOLLOW_CONFIG    161
#define IDS_STR_SCHEME_SAVE_FAILED      162
#define IDS_STR_SCHEME_ACRYLIC_DARK     163
#define IDS_STR_SCHEME_NORMAL_DARK      164
#define IDC_SCHEMA_LIST                 1000
#define IDC_SCHEMA_DESCRIPTION          1001
#define IDC_GET_SCHEMATA                1002
#define IDC_HOTKEYS                     1003
#define IDC_SCHEMA_SEARCH               1140
#define IDC_SCHEMA_DETAIL_NAME          1141
#define IDC_SCHEMA_DETAIL_STATUS        1142
#define IDC_SCHEMA_DETAIL_VERSION       1143
#define IDC_SCHEMA_DETAIL_SOURCE        1144
#define IDC_SCHEMA_DETAIL_UPDATE        1145
#define IDC_SCHEMA_UPDATE_SETTINGS      1146
#define IDC_SCHEMA_RESTORE_PACKAGE      1147
#define IDC_MODEL_GROUP                 1148
#define IDC_MODEL_NAME                  1149
#define IDC_MODEL_DESCRIPTION           1150
#define IDC_MODEL_SOURCE                1151
#define IDC_MODEL_NOTE                  1152
#define IDC_MODEL_DOWNLOAD              1153
#define IDC_MODEL_SECONDARY             1154
#define IDC_MODEL_PROGRESS              1155
#define IDC_MODEL_PROGRESS_TEXT         1156
#define IDC_AUTO_SCHEME_UPDATES         1157
#define IDC_CHECK_SCHEME_UPDATES        1158
#define IDC_IMPORT_SCHEME               1159
#define IDC_ADD_SCHEME_URL              1160
#define IDC_SCHEMA_DETAIL_GROUP         1161
#define IDC_UPDATE_STATUS               1162
#define IDC_SCHEMA_PROJECT_LINKS        1163
#define IDC_ADD_SCHEMA_GROUP            1164
#define IDC_USER_DATA_FOLDER            1165
#define IDC_HOTKEY_HINT                 1166
#define IDC_INPUT_MODE_LABEL            1167
#define IDC_INPUT_MODE                  1168
#define IDC_HOTKEY_GRAVE                1169
#define IDC_HOTKEY_OR                   1170
#define IDC_HOTKEY_F4                   1171
#define IDC_USER_DATA_LABEL             1172
#define IDD_PACKAGE_UPDATES             206
#define IDD_STATUS_ICON_SETTING         207
#define IDC_UPDATE_SCHEME               1173
#define IDC_UPDATE_MODEL                1174
#define IDC_UPDATE_SUMMARY              1175
#define IDC_UPDATE_SCHEME_GROUP         1176
#define IDC_UPDATE_MODEL_GROUP          1177
#define IDC_SCHEMA_AUTHOR               1178
#define IDC_SWITCHER_TITLE              1179
#define IDC_SCHEMA_LIST_PANEL           1180
#define IDC_SCHEMA_LIST_LABEL           1181
#define IDC_SCHEMA_DETAIL_LABEL         1182
#define IDC_SCHEMA_SHORTCUT_DIVIDER     1183
#define IDC_SCHEMA_FOOTER_DIVIDER       1184
#define IDC_HOTKEY_PLUS                 1185
#define IDC_SCHEMA_LAST_CHECK           1186
#define IDC_SCHEMA_SHORTCUT_LABEL       1187
#define IDC_MODEL_DOWNLOAD_STATUS       1188
#define IDC_STATUS_TITLE                1189
#define IDC_STATUS_RESTORE              1190
#define IDC_STATUS_BASE_TITLE           1191
#define IDC_STATUS_CHINESE_LABEL        1192
#define IDC_STATUS_CHINESE_ICON         1193
#define IDC_STATUS_CHINESE_CHANGE       1194
#define IDC_STATUS_ENGLISH_LABEL        1195
#define IDC_STATUS_ENGLISH_ICON         1196
#define IDC_STATUS_ENGLISH_CHANGE       1197
#define IDC_STATUS_CAPS_TITLE            1198
#define IDC_STATUS_CAPS_AUTOMATIC       1199
#define IDC_STATUS_CAPS_CUSTOM          1200
#define IDC_STATUS_BADGE_LETTER         1201
#define IDC_STATUS_BADGE_DOT            1202
#define IDC_STATUS_AUTO_CHINESE_ICON    1203
#define IDC_STATUS_AUTO_CHINESE_LABEL   1204
#define IDC_STATUS_AUTO_ENGLISH_ICON    1205
#define IDC_STATUS_AUTO_ENGLISH_LABEL   1206
#define IDC_STATUS_CHINESE_CAPS_LABEL   1207
#define IDC_STATUS_CHINESE_CAPS_ICON    1208
#define IDC_STATUS_CHINESE_CAPS_CHANGE  1209
#define IDC_STATUS_ENGLISH_CAPS_LABEL   1210
#define IDC_STATUS_ENGLISH_CAPS_ICON    1211
#define IDC_STATUS_ENGLISH_CAPS_CHANGE  1212
#define IDC_STATUS_TASKBAR_TITLE        1213
#define IDC_STATUS_TASKBAR_ICON         1214
#define IDC_STATUS_PREVIEW_CHINESE      1215
#define IDC_STATUS_PREVIEW_ENGLISH      1216
#define IDC_STATUS_PREVIEW_CHINESE_CAPS 1217
#define IDC_STATUS_PREVIEW_ENGLISH_CAPS 1218
#define IDC_STATUS_MESSAGE              1219
#define IDC_STATUS_APPLY                1220
#define IDC_STATUS_BASE_CARD            1221
#define IDC_STATUS_CAPS_CARD            1222
#define IDC_STATUS_TASKBAR_CARD         1223
#define IDD_FONT_SETTING                208
#define IDC_FONT_TITLE                  1224
#define IDC_FONT_RESTORE                1225
#define IDC_FONT_EDITOR_CARD            1226
#define IDC_FONT_EDITOR_TITLE           1227
#define IDC_FONT_ROLE_LABEL             1228
#define IDC_FONT_ROLE                   1229
#define IDC_FONT_LANGUAGE_LABEL         1230
#define IDC_FONT_LANGUAGE               1231
#define IDC_FONT_FAMILY_LABEL           1232
#define IDC_FONT_SEARCH                 1233
#define IDC_FONT_FAMILY                 1234
#define IDC_FONT_POINT_LABEL            1235
#define IDC_FONT_POINT                  1236
#define IDC_FONT_SHAPE_LABEL            1237
#define IDC_FONT_SHAPE_REGULAR          1238
#define IDC_FONT_SHAPE_BOLD             1239
#define IDC_FONT_SHAPE_ITALIC            1240
#define IDC_FONT_PREVIEW_CARD           1241
#define IDC_FONT_PREVIEW_TITLE          1242
#define IDC_FONT_PREVIEW_HORIZONTAL     1243
#define IDC_FONT_PREVIEW_VERTICAL       1244
#define IDC_FONT_PREVIEW                1245
#define IDC_FONT_MESSAGE                1246
#define IDC_FONT_APPLY                  1247
#define IDC_APPEARANCE_CARD             1248
#define IDC_APPEARANCE_LIGHT_PREVIEW_LABEL 1249
#define IDC_APPEARANCE_DARK_PREVIEW_LABEL 1250
#define IDC_COLOR_SCHEME                1004
#define IDC_SELECT_FONT                 1005
#define IDC_PREVIEW                     1006
#define IDC_USER_DICT_LIST              1007
#define IDC_BACKUP                      1008
#define IDC_RESTORE                     1009
#define IDC_EXPORT                      1010
#define IDC_IMPORT                      1011
#define IDC_STATIC1                     -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        209
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1251
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif

#define IDS_APPEARANCE_ALL 180
#define IDS_APPEARANCE_BASE 181
#define IDS_APPEARANCE_CUSTOM 182
#define IDS_APPEARANCE_MIXED 183
#define IDS_APPEARANCE_CURRENT 184
#define IDS_APPEARANCE_ACRYLIC 185
#define IDS_APPEARANCE_NORMAL 186
#define IDS_APPEARANCE_LIGHT 187
#define IDS_APPEARANCE_DARK 188
#define IDS_APPEARANCE_SAMPLE 189
#define IDS_STR_SCHEME_DEPLOY_FAILED 190
#define IDS_APPEARANCE_TITLE 191
#define IDC_APPEARANCE_TITLE 1133
#define IDC_COLOR_FAMILY 1100
#define IDC_COLOR_LIGHT 1110
#define IDC_COLOR_DARK 1111
#define IDC_ACRYLIC_ENABLED 1121
#define IDC_EDIT_SINGLE 1122
#define IDC_LIGHT_LABEL 1123
#define IDC_DARK_LABEL 1124
#define IDC_PREVIEW_LIGHT 1128
#define IDC_PREVIEW_DARK 1129
#define IDC_APPLY 1131
#define IDC_RESTORE_APPEARANCE 1132
#define IDS_APPEARANCE_ACRYLIC_HINT 192
#define IDS_APPEARANCE_NORMAL_HINT 193
#define IDS_APPEARANCE_ACRYLIC_PREVIEW 194
#define IDS_APPEARANCE_NORMAL_PREVIEW 195
#define IDS_APPEARANCE_SAMPLE_2 196
#define IDS_APPEARANCE_SAMPLE_3 197
#define IDS_APPEARANCE_ADVANCED 198
#define IDC_MATERIAL_HINT 1134
#define IDC_EDITOR_HINT 1135
#define IDC_PREVIEW_HINT 1136
#define IDC_SETTINGS_DIVIDER 1137
#define IDC_EDIT_GROUP 1138
#define IDC_SELECTION_HINT 1139
#define IDS_PALETTE_GROUP_HINT 199
#define IDS_PALETTE_SINGLE_HINT 200
#define IDS_PALETTE_CURRENT_DARK 201
#define IDS_PALETTE_CURRENT_LIGHT 202
#define IDS_PALETTE_CHOOSE 203
#define IDS_PALETTE_UNAVAILABLE 204
#define IDS_PALETTE_MISMATCH 205
