//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WeaselDeployer.rc
//
#define IDC_MYICON                      2
#define IDD_WEASELDEPLOYER_DIALOG       102
#define IDI_WEASELDEPLOYER              107
#define IDI_SMALL                       108
#define IDR_MAINFRAME                   128
#define IDD_SWITCHER_SETTING            129
#define IDD_STYLE_SETTING               130
#define IDI_DEPLOY                      131
#define IDD_DICT_MANAGEMENT             132
#define IDS_STR_WEASEL                  133
#define IDS_STR_SAD                     134
#define IDS_STR_HAPPY                   135
#define IDS_STR_NOT_REGULAR             136
#define IDS_STR_DEPLOYING_RESTARTREQ    137
#define IDS_STR_DEPLOYING_WAIT          138
#define IDS_STR_SEL_EXPORT_DICT_NAME    139
#define IDS_STR_ERREXPORT_SYNC_UV       140
#define IDS_STR_ERR_EXPORT_UNKNOWN      141
#define IDS_STR_ERR_EXPORT_SNAP_LOST    142
#define IDS_STR_ERR_UNKNOW              143
#define IDS_STR_ERR_UNKNOWN             143
#define IDS_STR_ERR_SUCCESS             144
#define IDS_STR_ERR_EXPORT_FILE_LOST    145
#define IDS_STR_SEL_IMPORT_DICT_NAME    146
#define IDS_STR_ERR_AT_LEAST_ONE_SEL    147
#define IDS_STR_SCHEMA_NAME             148
#define IDS_STR_OPEN                    149
#define IDS_STR_SAVE_AS                 150
#define IDS_STR_ALL_FILES               151
#define IDS_STR_TXT_FILES               152
#define IDS_STR_IMPORTED                153
#define IDS_STR_EXPORTED                154
#define IDS_STR_RECORD_COUNT            155
#define IDS_STR_DICT_SNAPSHOT           156
#define IDS_STR_KCSS_DICT_SNAPSHOT      157
#define IDS_STR_HELP                    158
#define IDS_STR_SCHEME_ACRYLIC          159
#define IDS_STR_SCHEME_NORMAL           160
#define IDS_STR_SCHEME_FOLLOW_CONFIG    161
#define IDS_STR_SCHEME_SAVE_FAILED      162
#define IDS_STR_SCHEME_ACRYLIC_DARK     163
#define IDS_STR_SCHEME_NORMAL_DARK      164
#define IDC_SCHEMA_LIST                 1000
#define IDC_SCHEMA_DESCRIPTION          1001
#define IDC_GET_SCHEMATA                1002
#define IDC_HOTKEYS                     1003
#define IDC_SCHEMA_SEARCH               1140
#define IDC_SCHEMA_DETAIL_NAME          1141
#define IDC_SCHEMA_DETAIL_STATUS        1142
#define IDC_SCHEMA_DETAIL_VERSION       1143
#define IDC_SCHEMA_DETAIL_SOURCE        1144
#define IDC_SCHEMA_DETAIL_UPDATE        1145
#define IDC_SCHEMA_UPDATE_SETTINGS      1146
#define IDC_SCHEMA_RESTORE_PACKAGE      1147
#define IDC_MODEL_GROUP                 1148
#define IDC_MODEL_NAME                  1149
#define IDC_MODEL_DESCRIPTION           1150
#define IDC_MODEL_SOURCE                1151
#define IDC_MODEL_NOTE                  1152
#define IDC_MODEL_DOWNLOAD              1153
#define IDC_MODEL_SECONDARY             1154
#define IDC_MODEL_PROGRESS              1155
#define IDC_MODEL_PROGRESS_TEXT         1156
#define IDC_AUTO_SCHEME_UPDATES         1157
#define IDC_CHECK_SCHEME_UPDATES        1158
#define IDC_IMPORT_SCHEME               1159
#define IDC_ADD_SCHEME_URL              1160
#define IDC_SCHEMA_DETAIL_GROUP         1161
#define IDC_COLOR_SCHEME                1004
#define IDC_SELECT_FONT                 1005
#define IDC_PREVIEW                     1006
#define IDC_USER_DICT_LIST              1007
#define IDC_BACKUP                      1008
#define IDC_RESTORE                     1009
#define IDC_EXPORT                      1010
#define IDC_IMPORT                      1011
#define IDC_STATIC1                     -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1162
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif

#define IDS_APPEARANCE_ALL 180
#define IDS_APPEARANCE_BASE 181
#define IDS_APPEARANCE_CUSTOM 182
#define IDS_APPEARANCE_MIXED 183
#define IDS_APPEARANCE_CURRENT 184
#define IDS_APPEARANCE_ACRYLIC 185
#define IDS_APPEARANCE_NORMAL 186
#define IDS_APPEARANCE_LIGHT 187
#define IDS_APPEARANCE_DARK 188
#define IDS_APPEARANCE_SAMPLE 189
#define IDS_STR_SCHEME_DEPLOY_FAILED 190
#define IDS_APPEARANCE_TITLE 191
#define IDC_APPEARANCE_TITLE 1133
#define IDC_COLOR_FAMILY 1100
#define IDC_COLOR_LIGHT 1110
#define IDC_COLOR_DARK 1111
#define IDC_ACRYLIC_ENABLED 1121
#define IDC_EDIT_SINGLE 1122
#define IDC_LIGHT_LABEL 1123
#define IDC_DARK_LABEL 1124
#define IDC_PREVIEW_LIGHT 1128
#define IDC_PREVIEW_DARK 1129
#define IDC_APPLY 1131
#define IDC_RESTORE_APPEARANCE 1132
#define IDS_APPEARANCE_ACRYLIC_HINT 192
#define IDS_APPEARANCE_NORMAL_HINT 193
#define IDS_APPEARANCE_ACRYLIC_PREVIEW 194
#define IDS_APPEARANCE_NORMAL_PREVIEW 195
#define IDS_APPEARANCE_SAMPLE_2 196
#define IDS_APPEARANCE_SAMPLE_3 197
#define IDS_APPEARANCE_ADVANCED 198
#define IDC_MATERIAL_HINT 1134
#define IDC_EDITOR_HINT 1135
#define IDC_PREVIEW_HINT 1136
#define IDC_SETTINGS_DIVIDER 1137
#define IDC_EDIT_GROUP 1138
#define IDC_SELECTION_HINT 1139
#define IDS_PALETTE_GROUP_HINT 199
#define IDS_PALETTE_SINGLE_HINT 200
#define IDS_PALETTE_CURRENT_DARK 201
#define IDS_PALETTE_CURRENT_LIGHT 202
#define IDS_PALETTE_CHOOSE 203
#define IDS_PALETTE_UNAVAILABLE 204
#define IDS_PALETTE_MISMATCH 205
